stages:
  load_data:
    cmd : python src/stage_01_load_save.py --config=config/config.yaml
    deps:
      - src/stage_01_load_save.py
      - config/config.yaml
      - src/utils/all_utils.py
    outs:
      -  artifacts/raw_local_dir/data.csv

  split_data:
    cmd : python src/stage_02_split_save.py --config=config/config.yaml --params=params.yaml
    deps:
    - src/stage_02_split_save.py 
    - config/config.yaml
    - src/utils/all_utils.py
    - artifacts/raw_local_dir/data.csv
    params:
    - base.random_state
    - base.test_size
    outs:
    - artifacts/split_data_dir/train.csv
    - artifacts/split_data_dir/test.csv

      


